trigger:
- master

stages:
- stage: UnitTesting
  jobs:
  - job: BackendUnitTesting
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo Run your very cool test suite here
  - job: FrontendUnitTesting
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo The fun is in the js tests

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      imageName: 'ciberado/pokemon-dashboard'
      tag: '\$(Build.BuildId)'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'ciberado'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          \$(tag)
- stage: Compliance
  jobs:
  - job: ExecuteSecurityCompliance
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo Now trigger that fancy security tool execution
