trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      imageName: 'ciberado/pokemon-dashboard'
      tag: '\$(Build.BuildId)'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'ciberado'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
