# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: UnitTesting
  jobs:
  - job: BackendUnitTesting
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo Run your very cool test suite here
  - job: FrontendUnitTesting
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo The fun is in the js tests

- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'ciberado/pokemon-dashboard'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Compliance
  jobs:
  - job: ExecuteSecurityCompliance
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo Now trigger that fancy security tool execution